### ISSUE TITLE
pipetty: set PAGER=cat?

### ISSUE THREAD

**Issue by jwilk** [kilobyte/colorized-logs#2]
Some commands (`git`, `dmesg -H`), spawn a pager when running on a tty, which doesn't work correctly under pipetty.
As a work-around, you can put `PAGER=cat` in environment. I wonder if it would make sense for pipetty to do this automatically.

**Comment by kilobyte** [comment]
On one hand, it feels wrong to add a hardcoded configuration override to a tool operating at low level.  But then, you're right.

I can think of no use cases that'd be broken by forcing ``PAGER=cat`` — even if someone abuses PAGER for some other purposes, it can be done just as well outside pipetty.
