### ISSUE TITLE
Add an option to change style= used for generating html

### ISSUE THREAD

**Issue by pacho2** [kilobyte/colorized-logs#3]
Hello,

We are having some issues with wrapping in generated html file because we have some long lines trying to even draw some things using ansi colors and symbols. Currently, white-space:pre-wrap is hardcoded causing the cartoons to be deformed. 

For now we are workarounding this with a sed line to change 's/white-space:pre-wrap/white-space:pre/', but maybe some people would also welcome this to be configured by an option to not need to play with sed for changing this or other style settings.
To this end, maybe an option to allow us to specify the full "style=" to be used would be really useful.

Thanks a lot

**Comment by kilobyte** [comment]
Good idea, will do.  Just a bikeshed-painting question: what would a good option be? ``-w`` is taken.

Even that full style= specifier might be good, too.

(About to depart for a week, likely won't respond until then.)

**Comment by pacho2** [comment]
I would choose simply --style= (and probably short -s version)... but feel free to choose a different one if you prefer :)
