### ISSUE TITLE
Platforms without openpty(3), i.e. just POSIX

### ISSUE THREAD

**Issue by polluks** [kilobyte/colorized-logs#8]
There should be a `#ifdef HAVE_FUNC_OPENPTY` in pipetty.c.

**Comment by kilobyte** [comment]
Do you know a platform which does *not* have it?  I've dropped such support in 0d35ee486525c8bd316d9e4ea27fae269947883d.

**Comment by polluks** [comment]
I see. Yesterday I was trying to do a MorphOS port, even more exotic than IRIX :-)
Maybe a `return 127` is sufficient, I don't need full posix_openpt(3) support.

**Comment by kilobyte** [comment]
Right, so old IRIX code would be unlikely to help.

Without some way to spawn a PTY, `pipetty` (and `lesstty`) can't work, but the reading tools will still be functional.

**Comment by polluks** [comment]
I would like a fallback to make Make happy, no extra code.

**Comment by kilobyte** [comment]
Would:
`make ttyrec2ansi ansi2txt ansi2html`
be enough for you?

**Comment by polluks** [comment]
Well, we have a sophisticated tool like CMake but a non-standard machine requires a special calling convention?

**Comment by kilobyte** [comment]
The problem, it's very hard to add proper detection logic if you're unable to test it.  At that point, it'd probably be hardly easier than to add actual support.

I don't have access to such a machine, and I see it's proprietary so no running in qemu either.

**Comment by polluks** [comment]
> Would:
> `make ttyrec2ansi ansi2txt ansi2html`
> be enough for you?

ok...
https://www.youtube.com/watch?v=1z5R53k_zkE :-)

**Comment by kilobyte** [comment]
It's nice it works in qemu — but, is there a way to get the payload?

**Comment by polluks** [comment]
The demo works 30 min https://www.morphos-team.net/downloads
